#!/usr/bin/env python3
#-*- coding: utf-8 -*-
import bagpy
from bagpy  import bagreader
import pandas as pd
import seaborn as sea
import matplotlib.pyplot as plt
import numpy as np
 
 

A=bagreader('/home/srinidhi/catkin_ws/src/Data/walkingfield.bag')
B=bagreader('/home/srinidhi/catkin_ws/src/Data/stdsnell.bag')

A.topic_table
B.topic_table

Lat1= 42.33895243938416
long1= -71.08793531846682

Lat2= 42.33895256765
long2= -71.08793567878

x = A.message_by_topic('/gps')
y = B.message_by_topic('/gps')


df_x = pd.read_csv(x)
df_y = pd.read_csv(y)

x1=df_x['Latitude_std']= df_x['Latitude']
x2=df_x['Longitude_std']= df_x['Longitude']

y1=df_y['Latitude_std']= df_y['Latitude']
y2=df_y['Longitude_std']= df_y['Longitude']


#la1= np.radians(Lat1)
#lon1=np.radians(long1)

#la2 = np.radians(x1)
#lon2 =np.radians(x2)

#p= np.sin(((la2 - la1)/2))
#q= np.cos(la1)*np.cos(la2)
#r= np.sin((lon2 -lon1)/2)

#a = np.sqrt((p*p)+(q*(r*r)))
#b = np.arcsin(a) 
#error1= 2*(6371*1000)*b
#plt.hist(error1, edgecolor='black')

la12= np.radians(Lat2)
lon12=np.radians(long2)

la2 = np.radians(y1)
lon2 =np.radians(y2)

p= np.sin(((la2 - la12)/2))
q= np.cos(la12)*np.cos(la2)
r= np.sin((lon2 -lon12)/2)

a = np.sqrt((p*p)+(q*(r*r)))
b = np.arcsin(a)
error2= 2*(6371*1000)*b
plt.hist(error2, edgecolor='black')



plt.show()
